#!/usr/bin/env python
"""Crosswalk the playbook's diligence prompts against the review-table corpus.

    python scripts/crosswalk.py --calibrate     # check the scorer against known-good pairs
    python scripts/crosswalk.py                 # both directions
    python scripts/crosswalk.py --out playbook/crosswalk.json

Two directions, and the second is the one nobody runs:

- **Playbook to corpus** — which fields the practice asks for that no column answers.
- **Corpus to playbook** — which columns answer nothing the playbook asks and feed no derived
  artifact. Those are columns filled on every row of every matter for no reader.

**The four moves are answered by different layers.** Section 3.4 provides prompts for
(i) summarizing, (ii) identifying risks, (iii) flagging missing items and (iv) synthesizing.
Only (i) and the factual half of (ii) are extraction columns: `00a` section 10 reserves rating
and consequence for a human, missing items are the coverage register, and synthesis is a
derived artifact. Scoring all four against extraction columns reports design as deficiency.

**Provenance.** The playbook was substantially model-generated by a senior partner rather than
written from observed practice, so agreement with the corpus is evidence that two syntheses
agree, not that either is right.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from diligence_kernel import crosswalk as cw  # noqa: E402
from diligence_kernel import db, env  # noqa: E402
from diligence_kernel.corpus.loader import load_corpus  # noqa: E402
from diligence_kernel.derive.artifacts import ARTIFACTS  # noqa: E402

GREEN, RED, YELLOW, DIM, BOLD, RESET = (
    "\033[32m",
    "\033[31m",
    "\033[33m",
    "\033[2m",
    "\033[1m",
    "\033[0m",
)

#: Which corpus tables answer each playbook prompt.
#:
#: **Prompt boundaries are not table boundaries.** 3.4.1 is titled "Summarize a Corporate
#: Organizational Document" and asks for capital structure, liquidation preferences and
#: anti-dilution — which the corpus places in Capitalization (03), not Corporate (02).
TABLES_OF_PROMPT: dict[str, tuple[str, ...]] = {
    "3.4.1": ("02", "03"),
    "3.4.2": ("02", "03"),
    "3.4.3": ("02", "03"),
    "3.4.4": ("02", "03"),
    "3.4.5": ("01", "07"),
    "3.4.6": ("01", "07"),
    "3.4.7": ("01", "07"),
    "3.4.8": ("10", "11", "12"),
    "3.4.9": ("10", "11", "12"),
    "3.4.10": ("08", "09", "04"),
    "3.4.11": ("08", "09"),
    "3.4.12": ("13", "14"),
    "3.4.13": ("15", "17"),
    "3.4.14": ("16", "17"),
    "3.4.15": ("24", "25"),
    "3.4.16": (),  # financial statements: 00a places these out of scope
}

HUMAN = re.compile(
    r"\brate\b|\brating\b|high,? medium|likelihood|mitigat|recommend|prioriti|materiality|"
    r"deal consequence|significance|severity|assess the risk",
    re.I,
)
SYNTHESIS = re.compile(
    r"synthesi[sz]|memo\b|across (?:all|the) |portfolio-level|aggregate|overall summary|"
    r"executive summary|prepare a summary|organi[sz]ed by",
    re.I,
)
MISSING = re.compile(r"missing|not produced|absent|checklist|request list|follow-up request", re.I)

#: Pairs confirmed by reading the corpus, used to calibrate the threshold. Each is a playbook
#: concept whose column the lexical scorer missed.
KNOWN_PAIRS = [
    ("drag-along, tag-along, co-sale rights on transfer of equity interests", "02", "Drag-Along"),
    ("anti-dilution provisions in the capital structure", "03", "Anti-Dilution Protection"),
    ("liquidation preferences of each class of stock", "03", "Liquidation Preference"),
    ("right of first refusal on transfer of shares", "02", "Transfer Restrictions"),
    ("board composition, quorum and voting requirements", "02", "Governing Body Composition"),
    ("change-of-control provisions and consent requirements", "01", "Change of Control Treatment"),
    ("assignment clause and anti-assignment restrictions", "01", "Assignment Restriction"),
    ("governing law of the agreement", "01", "Governing Law"),
    ("severance entitlement on termination", "08", "Severance Entitlement"),
    ("lease expiry and renewal options", "13", "Renewal Options"),
]


def answered_by(field: str) -> str:
    if HUMAN.search(field):
        return "human"
    if MISSING.search(field):
        return "missing"
    if SYNTHESIS.search(field):
        return "synthesis"
    return "extraction"


def load_columns(conn) -> list[dict]:
    return [
        {
            "table": r["number"],
            "name": r["name"],
            "text": cw.column_text(r["name"], r["purpose"], r["title"]),
        }
        for r in conn.execute(
            """SELECT t.number, t.title, cd.name, cd.purpose FROM column_def cd
               JOIN review_table t ON t.id = cd.table_id ORDER BY t.number, cd.position"""
        )
    ]


def calibrate(columns: list[dict], vectors: dict) -> int:
    """Score the pairs a human confirmed, so the threshold is set on evidence."""
    print(f"{BOLD}Calibration — pairs confirmed by reading the corpus{RESET}\n")
    ranks, scores = [], []
    for probe, table, name in KNOWN_PAIRS:
        pv = vectors.get(probe)
        if pv is None:
            continue
        ordered = sorted(
            ((cw.cosine(pv, vectors[c["text"]]), c) for c in columns if c["text"] in vectors),
            key=lambda kv: -kv[0],
        )
        position = next(
            (i for i, (_, c) in enumerate(ordered, 1) if c["table"] == table and c["name"] == name),
            None,
        )
        score = next((s for s, c in ordered if c["table"] == table and c["name"] == name), 0.0)
        ranks.append(position or 999)
        scores.append(score)
        top = ordered[0][1]
        mark = (
            GREEN + "ok " + RESET
            if position == 1
            else (
                YELLOW + f"#{position}" + RESET
                if position and position <= 5
                else RED + "miss" + RESET
            )
        )
        print(f"  {mark} {probe[:52]:54s} {score:.2f}  top: {top['table']} {top['name'][:28]}")
    hit1 = sum(1 for r in ranks if r == 1)
    hit5 = sum(1 for r in ranks if r <= 5)
    print(
        f"\n  expected column ranked first: {hit1}/{len(ranks)}   in the top five: {hit5}/{len(ranks)}"
    )
    if scores:
        print(
            f"  score on the expected column: min {min(scores):.2f}, mean {sum(scores) / len(scores):.2f}"
        )
        print(f"  {DIM}threshold {cw.DEFAULT_THRESHOLD} admits a pair scoring above it{RESET}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--playbook", default="playbook/corporate-ma-3.4.json")
    parser.add_argument("--calibrate", action="store_true")
    parser.add_argument("--threshold", type=float, default=cw.DEFAULT_THRESHOLD)
    parser.add_argument("--show", type=int, default=2)
    parser.add_argument("--out", help="Write the crosswalk as JSON.")
    parser.add_argument("--quiet", action="store_true", help="Summary only.")
    args = parser.parse_args()

    env.load()
    book = json.loads(Path(args.playbook).read_text())
    conn = db.connect(Path(tempfile.mkdtemp()) / "corpus.db")
    load_corpus(conn, REPO / "review-table-prompts")
    columns = load_columns(conn)

    fields = [(p["id"], f) for p in book["prompts"] for f in p["fields"]]
    texts = [c["text"] for c in columns] + [f for _, f in fields] + [p for p, _, _ in KNOWN_PAIRS]
    print(
        f"{DIM}embedding {len(set(texts))} texts ({cw.DEFAULT_MODEL}), cached at "
        f"{cw.cache_path()}{RESET}"
    )
    vectors = cw.embed_all(texts)

    if args.calibrate:
        return calibrate(columns, vectors)

    results: list[cw.FieldResult] = []
    matched: set[tuple[str, str]] = set()
    for prompt in book["prompts"]:
        scope = set(TABLES_OF_PROMPT.get(prompt["id"], ()))
        pool = [c for c in columns if c["table"] in scope]
        if not args.quiet:
            print(f"\n{BOLD}{prompt['id']}{RESET}  {prompt['title'][:64]}")
            print(
                f"        tables {sorted(scope) or '— outside the corpus —'}; {len(pool)} columns"
            )
        for f in prompt["fields"]:
            layer = answered_by(f)
            r = cw.FieldResult(prompt["id"], f, layer)
            if layer == "extraction" and pool:
                fv = vectors.get(f)
                if fv is not None:
                    r.matches = cw.rank(fv, pool, vectors, top=args.show, threshold=args.threshold)
                    for m in r.matches:
                        matched.add((m.table, m.column))
            results.append(r)
            if args.quiet:
                continue
            if layer != "extraction":
                print(f"    {DIM}{layer[:4]:4s}{RESET} {f[:54]:56s} answered by the {layer} layer")
            elif r.covered:
                shown = "; ".join(f"{m.table} {m.column} {m.score:.2f}" for m in r.matches[:2])
                print(f"    {GREEN}ok  {RESET} {f[:54]:56s} {shown[:56]}")
            else:
                best = (
                    f"best {r.matches[0].table} {r.matches[0].column} {r.best:.2f}"
                    if r.matches
                    else "nothing above threshold"
                )
                print(f"    {RED}GAP {RESET} {f[:54]:56s} {best[:56]}")

    # --- corpus to playbook -------------------------------------------------------------
    #
    # Computed per column against every field in scope, not from the fields' top-N lists. A
    # column that is any field's third-best answer still answers it; ranking it out of a
    # top-two list and then calling it unread is an artefact of the list length, not a finding.
    artifact_words = {w for s in ARTIFACTS.values() for p in s.column_patterns for w in p.split()}
    fields_by_table: dict[str, list[str]] = defaultdict(list)
    for prompt in book["prompts"]:
        for table in TABLES_OF_PROMPT.get(prompt["id"], ()):
            fields_by_table[table].extend(
                f for f in prompt["fields"] if answered_by(f) == "extraction"
            )

    unread: dict[str, list[str]] = defaultdict(list)
    best_for_column: dict[tuple[str, str], float] = {}
    for c in columns:
        cv = vectors.get(c["text"])
        relevant = fields_by_table.get(c["table"], [])
        best = 0.0
        if cv is not None:
            for f in relevant:
                fv = vectors.get(f)
                if fv is not None:
                    best = max(best, cw.cosine(cv, fv))
        best_for_column[(c["table"], c["name"])] = best
        if best >= args.threshold:
            continue
        if any(w in c["name"].lower() for w in artifact_words):
            continue  # feeds a derived artifact even where no playbook field asks for it
        unread[c["table"]].append(c["name"])

    extraction = [r for r in results if r.layer == "extraction"]
    covered = [r for r in extraction if r.covered]
    print(f"\n{BOLD}Summary{RESET}")
    print(f"  playbook fields                {len(results)}")
    for layer in ("extraction", "human", "missing", "synthesis"):
        n = sum(1 for r in results if r.layer == layer)
        print(f"    answered by {layer:12s} {n}")
    print(
        f"  extraction fields covered      {len(covered)}/{len(extraction)} "
        f"({len(covered) / max(1, len(extraction)):.0%})"
    )
    print(f"  corpus columns                 {len(columns)}")
    answering = sum(1 for v in best_for_column.values() if v >= args.threshold)
    print(f"  answering a playbook field     {answering}")
    print(f"  answering nothing read         {sum(len(v) for v in unread.values())}")
    print(f"\n  {DIM}{book['provenance']}{RESET}")

    if args.out:
        payload = {
            "model": cw.DEFAULT_MODEL,
            "threshold": args.threshold,
            "provenance": book["provenance"],
            "fields": [
                {
                    "prompt": r.prompt_id,
                    "field": r.field,
                    "layer": r.layer,
                    "covered": r.covered,
                    "matches": [
                        {"table": m.table, "column": m.column, "score": round(m.score, 3)}
                        for m in r.matches
                    ],
                }
                for r in results
            ],
            "columns_answering_nothing": {k: sorted(v) for k, v in sorted(unread.items())},
            "column_best_score": {
                f"{t} {n}": round(v, 3) for (t, n), v in sorted(best_for_column.items())
            },
        }
        Path(args.out).write_text(json.dumps(payload, indent=2))
        print(f"\n  written to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
