#!/usr/bin/env python
"""Extract the playbook's diligence prompts into a data file.

    python scripts/extract_playbook.py --pdf <path> --out playbook/corporate-ma-3.4.json

Section 3.4 provides, for each workstream, prompts for (i) summarizing a document,
(ii) identifying key risks, (iii) flagging missing items against a checklist, and
(iv) synthesizing findings. Each prompt enumerates the fields it asks for; those bullets are
what a crosswalk against the corpus can actually compare.

The output is committed so the crosswalk does not depend on the PDF, which is the firm's own
document and is not in this repository.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PROMPT = re.compile(r"Prompt (3\.4\.\d{1,2}):\s*(.+?)(?=\n)", re.S)
NOISE = re.compile(r"Harvey Prompt Playbook — Corporate & M&A Practice\n|^Page \d+$", re.M)
#: A hyphen at a line break, which the extractor leaves mid-word. "drag-\nalong" becomes
#: "drag- along" and then two tokens, so `drag-along` no longer matches the column of that
#: name. The same artefact that made a correct Verbatim quotation fail its own check.
HYPHEN_BREAK = re.compile(r"([a-z])-\s*\n\s*([a-z])")

#: The four-move pattern section 3.4 states on its first page.
MOVES = {
    "summarize": "(i) summarize an individual document",
    "risks": "(ii) identify key risks",
    "missing": "(iii) flag missing items against a checklist",
    "synthesize": "(iv) synthesize findings across documents",
}


def classify_move(title: str) -> list[str]:
    """Which of the four moves a prompt performs. Several perform more than one."""
    t = title.lower()
    moves = []
    if "summarize" in t or "summarise" in t:
        moves.append("summarize")
    if "risk" in t or "identify key" in t or "issues" in t:
        moves.append("risks")
    if "missing" in t or "checklist" in t:
        moves.append("missing")
    if "synthesize" in t or "synthesise" in t or "across" in t:
        moves.append("synthesize")
    return moves or ["summarize"]


#: A bullet ends at the next bullet, a tip, the usage note, or the next prompt. It does not
#: end at a newline: the extractor wraps a single bullet across several lines.
_BULLET = re.compile(r"•\s*(.+?)(?=•|◦|When to use:|Prompt 3\.4\.|\Z)", re.S)
_ENUMERATED = re.compile(r"(?:^|\s)(\d{1,2})\.\s+(.+?)(?=\s\d{1,2}\.\s|When to use:|◦|\Z)", re.S)


def fields_of(body: str) -> list[str]:
    """The fields a prompt asks for.

    Most prompts bullet them; a few number them instead ("please: 1. Identify all material
    risks... 2. ..."). Both shapes are read, because a prompt whose fields are missed looks
    like a prompt the corpus fully covers.
    """
    out: list[str] = []
    for raw in _BULLET.findall(body):
        field = " ".join(raw.split()).strip(" .;:")
        if field and not field.lower().startswith(("tip:", "when to use")) and len(field) > 5:
            out.append(field)
    if not out:
        for _, raw in _ENUMERATED.findall(body):
            field = " ".join(raw.split()).strip(" .;:")
            if field and len(field) > 5:
                out.append(field)
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pdf", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--first-page", type=int, default=37)
    parser.add_argument("--last-page", type=int, default=52)
    args = parser.parse_args()

    import pdfplumber

    with pdfplumber.open(args.pdf) as pdf:
        pages = pdf.pages[args.first_page - 1 : args.last_page]
        text = "\n".join((p.extract_text() or "") for p in pages)
    text = HYPHEN_BREAK.sub(r"\1-\2", NOISE.sub("", text))

    marks = [(m.group(1), " ".join(m.group(2).split()), m.start()) for m in PROMPT.finditer(text)]
    prompts = []
    for index, (number, title, start) in enumerate(marks):
        end = marks[index + 1][2] if index + 1 < len(marks) else len(text)
        body = text[start:end]
        usage = re.search(r"When to use:\s*(.+?)(?=\s*◦|\Z)", body, re.S)
        prompts.append(
            {
                "id": number,
                "title": title,
                "moves": classify_move(title),
                "fields": fields_of(body),
                "when_to_use": " ".join(usage.group(1).split()) if usage else None,
            }
        )

    payload = {
        "source": Path(args.pdf).name,
        "section": "3.4 Due Diligence Review",
        "moves": MOVES,
        "provenance": (
            "The playbook was substantially model-generated by a senior partner, not written "
            "from observed practice. Agreement with the corpus is evidence that two syntheses "
            "agree, not that either is right."
        ),
        "prompts": prompts,
    }
    Path(args.out).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    total = sum(len(p["fields"]) for p in prompts)
    print(f"{len(prompts)} prompts, {total} enumerated fields -> {args.out}")
    for p in prompts:
        print(
            f"  {p['id']:8s} {len(p['fields']):2d} fields  {'/'.join(p['moves']):28s} {p['title'][:52]}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
